---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bundle exec jekyll serve`. If you change this file, please restart the server
# process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MAYSL
email: shaug-maysl@wumpus.org
# Default is your site title.
description: >-
  Mountain Area Youth Soccer League
#author: O'Shaughnessy Evans
# the subpath of your site, e.g. /blog
baseurl: ""
# base hostname & protocol for your site, e.g. http://example.com
url: https://maysl.soccer
source_url: https://github.com/oshaughnessy/maysl.soccer/

# Build settings
# theme: minima
# theme: jekyll-theme-tactile
# theme: jekyll-theme-persephone
# remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: erlzhang/jekyll-theme-persephone
remote_theme: mmistakes/minimal-mistakes@4.24.0
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .minimal-mistakes
  - .persephone
  - Makefile
  - '**/Makefile'
  - '.*.swp'
  - '.*.swo'

# # Your social accounts.
#social:
#  github: oshaughnessy/maysl.soccer
#  twitter: ohshaughnessy
#  instagram: instagram_username
#  linkedin: linkedin_username
#  weibo: weibo_username

# Theme Settings

# See also: https://mmistakes.github.io/minimal-mistakes/docs/configuration

# Your site's logo. Will be shown on the left top of your page.
#logo: /files/crazy-cleats.svg
#logo: /files/yhs-field-1.png
#logo: /files/maysl-logo-sidebar.png
logo: /files/maysl-logo.png
# If the images of our blog are stored in an external cloud,
# you can use the jekyll-img-prefix plugin and set your image's base URL here.
# img_prefix: https://your-img-cdn.com
# # The RSS link of your blog.
# rss: "/feed.xml"

minimal_mistakes_skin: maysl

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#seo-social-sharing-and-analytics-settings
twitter:
  username: ohshaughnessy
facebook:
  username: mountainyouthsoccer
og_image: /files/maysl-logo-small.png
social:
  type: Organization # Person or Organization (defaults to Person)
  name: Mountain Area Youth Soccer League # If the user or organization name differs from the site's name
  links:
    - https://www.facebook.com/mountainyouthsoccer
    #- https://twitter.com/yourTwitter
    #- https://instagram.com/yourProfile
    #- https://www.linkedin.com/in/yourprofile
footer:
  links:
    #- label: Twitter
    #  icon: fab fa-fw fa-twitter-square
    #  url: https://twitter.com/mmistakes
    #- label: Instagram
    #  icon: fab fa-fw fa-instagram
    #  url: https://instagram.com/mmistakes
    - label: Facebook
      icon: fab fa-fw fa-facebook
      url: https://facebook.com/mountainyouthsoccer
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/oshaughnessy/maysl.soccer

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      #sidebar: 
      #  nav: sidebar
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true

include: ["_pages"]

#paginate: 5  # amount of posts to show
#paginate_path: /updates/page:num
